# Generated by Django 2.2 on 2021-07-27 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delights_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delightorder',
            name='delight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delight_orders', to='delights_app.Delight'),
        ),
    ]
